#!/bin/bash

# remove all svg but pizza, walk, apps, log-instagram, logo-github, logo-linkedin, document, link

rm ./www/svg/ios-add-circle-outline.svg
rm ./www/svg/ios-add-circle.svg
rm ./www/svg/ios-add.svg
rm ./www/svg/ios-airplane.svg
rm ./www/svg/ios-alarm.svg
rm ./www/svg/ios-albums.svg
rm ./www/svg/ios-alert.svg
rm ./www/svg/ios-american-football.svg
rm ./www/svg/ios-analytics.svg
rm ./www/svg/ios-aperture.svg
rm ./www/svg/ios-appstore.svg
rm ./www/svg/ios-archive.svg
rm ./www/svg/ios-arrow-back.svg
rm ./www/svg/ios-arrow-down.svg
rm ./www/svg/ios-arrow-dropdown-circle.svg
rm ./www/svg/ios-arrow-dropdown.svg
rm ./www/svg/ios-arrow-dropleft-circle.svg
rm ./www/svg/ios-arrow-dropleft.svg
rm ./www/svg/ios-arrow-dropright-circle.svg
rm ./www/svg/ios-arrow-dropright.svg
rm ./www/svg/ios-arrow-dropup-circle.svg
rm ./www/svg/ios-arrow-dropup.svg
rm ./www/svg/ios-arrow-forward.svg
rm ./www/svg/ios-arrow-round-back.svg
rm ./www/svg/ios-arrow-round-down.svg
rm ./www/svg/ios-arrow-round-forward.svg
rm ./www/svg/ios-arrow-round-up.svg
rm ./www/svg/ios-arrow-up.svg
rm ./www/svg/ios-at.svg
rm ./www/svg/ios-attach.svg
rm ./www/svg/ios-backspace.svg
rm ./www/svg/ios-barcode.svg
rm ./www/svg/ios-baseball.svg
rm ./www/svg/ios-basket.svg
rm ./www/svg/ios-basketball.svg
rm ./www/svg/ios-battery-charging.svg
rm ./www/svg/ios-battery-dead.svg
rm ./www/svg/ios-battery-full.svg
rm ./www/svg/ios-beaker.svg
rm ./www/svg/ios-bed.svg
rm ./www/svg/ios-beer.svg
rm ./www/svg/ios-bicycle.svg
rm ./www/svg/ios-bluetooth.svg
rm ./www/svg/ios-boat.svg
rm ./www/svg/ios-body.svg
rm ./www/svg/ios-bonfire.svg
rm ./www/svg/ios-book.svg
rm ./www/svg/ios-bookmark.svg
rm ./www/svg/ios-bookmarks.svg
rm ./www/svg/ios-bowtie.svg
rm ./www/svg/ios-briefcase.svg
rm ./www/svg/ios-browsers.svg
rm ./www/svg/ios-brush.svg
rm ./www/svg/ios-bug.svg
rm ./www/svg/ios-build.svg
rm ./www/svg/ios-bulb.svg
rm ./www/svg/ios-bus.svg
rm ./www/svg/ios-business.svg
rm ./www/svg/ios-cafe.svg
rm ./www/svg/ios-calculator.svg
rm ./www/svg/ios-calendar.svg
rm ./www/svg/ios-call.svg
rm ./www/svg/ios-camera.svg
rm ./www/svg/ios-car.svg
rm ./www/svg/ios-card.svg
rm ./www/svg/ios-cart.svg
rm ./www/svg/ios-cash.svg
rm ./www/svg/ios-cellular.svg
rm ./www/svg/ios-chatboxes.svg
rm ./www/svg/ios-chatbubbles.svg
rm ./www/svg/ios-checkbox-outline.svg
rm ./www/svg/ios-checkbox.svg
rm ./www/svg/ios-checkmark-circle-outline.svg
rm ./www/svg/ios-checkmark-circle.svg
rm ./www/svg/ios-checkmark.svg
rm ./www/svg/ios-clipboard.svg
rm ./www/svg/ios-clock.svg
rm ./www/svg/ios-close-circle-outline.svg
rm ./www/svg/ios-close-circle.svg
rm ./www/svg/ios-close.svg
rm ./www/svg/ios-cloud-circle.svg
rm ./www/svg/ios-cloud-done.svg
rm ./www/svg/ios-cloud-download.svg
rm ./www/svg/ios-cloud-outline.svg
rm ./www/svg/ios-cloud-upload.svg
rm ./www/svg/ios-cloud.svg
rm ./www/svg/ios-cloudy-night.svg
rm ./www/svg/ios-cloudy.svg
rm ./www/svg/ios-code-download.svg
rm ./www/svg/ios-code-working.svg
rm ./www/svg/ios-code.svg
rm ./www/svg/ios-cog.svg
rm ./www/svg/ios-color-fill.svg
rm ./www/svg/ios-color-filter.svg
rm ./www/svg/ios-color-palette.svg
rm ./www/svg/ios-color-wand.svg
rm ./www/svg/ios-compass.svg
rm ./www/svg/ios-construct.svg
rm ./www/svg/ios-contact.svg
rm ./www/svg/ios-contacts.svg
rm ./www/svg/ios-contract.svg
rm ./www/svg/ios-contrast.svg
rm ./www/svg/ios-copy.svg
rm ./www/svg/ios-create.svg
rm ./www/svg/ios-crop.svg
rm ./www/svg/ios-cube.svg
rm ./www/svg/ios-cut.svg
rm ./www/svg/ios-desktop.svg
rm ./www/svg/ios-disc.svg
rm ./www/svg/ios-done-all.svg
rm ./www/svg/ios-download.svg
rm ./www/svg/ios-easel.svg
rm ./www/svg/ios-egg.svg
rm ./www/svg/ios-exit.svg
rm ./www/svg/ios-expand.svg
rm ./www/svg/ios-eye-off.svg
rm ./www/svg/ios-eye.svg
rm ./www/svg/ios-fastforward.svg
rm ./www/svg/ios-female.svg
rm ./www/svg/ios-filing.svg
rm ./www/svg/ios-film.svg
rm ./www/svg/ios-finger-print.svg
rm ./www/svg/ios-fitness.svg
rm ./www/svg/ios-flag.svg
rm ./www/svg/ios-flame.svg
rm ./www/svg/ios-flash-off.svg
rm ./www/svg/ios-flash.svg
rm ./www/svg/ios-flashlight.svg
rm ./www/svg/ios-flask.svg
rm ./www/svg/ios-flower.svg
rm ./www/svg/ios-folder-open.svg
rm ./www/svg/ios-folder.svg
rm ./www/svg/ios-football.svg
rm ./www/svg/ios-funnel.svg
rm ./www/svg/ios-gift.svg
rm ./www/svg/ios-git-branch.svg
rm ./www/svg/ios-git-commit.svg
rm ./www/svg/ios-git-compare.svg
rm ./www/svg/ios-git-merge.svg
rm ./www/svg/ios-git-network.svg
rm ./www/svg/ios-git-pull-request.svg
rm ./www/svg/ios-glasses.svg
rm ./www/svg/ios-globe.svg
rm ./www/svg/ios-grid.svg
rm ./www/svg/ios-hammer.svg
rm ./www/svg/ios-hand.svg
rm ./www/svg/ios-happy.svg
rm ./www/svg/ios-headset.svg
rm ./www/svg/ios-heart-dislike.svg
rm ./www/svg/ios-heart-empty.svg
rm ./www/svg/ios-heart-half.svg
rm ./www/svg/ios-heart.svg
rm ./www/svg/ios-help-buoy.svg
rm ./www/svg/ios-help-circle-outline.svg
rm ./www/svg/ios-help-circle.svg
rm ./www/svg/ios-help.svg
rm ./www/svg/ios-home.svg
rm ./www/svg/ios-hourglass.svg
rm ./www/svg/ios-ice-cream.svg
rm ./www/svg/ios-image.svg
rm ./www/svg/ios-images.svg
rm ./www/svg/ios-infinite.svg
rm ./www/svg/ios-information-circle-outline.svg
rm ./www/svg/ios-information-circle.svg
rm ./www/svg/ios-information.svg
rm ./www/svg/ios-jet.svg
rm ./www/svg/ios-journal.svg
rm ./www/svg/ios-key.svg
rm ./www/svg/ios-keypad.svg
rm ./www/svg/ios-laptop.svg
rm ./www/svg/ios-leaf.svg
rm ./www/svg/ios-list-box.svg
rm ./www/svg/ios-list.svg
rm ./www/svg/ios-locate.svg
rm ./www/svg/ios-lock.svg
rm ./www/svg/ios-log-in.svg
rm ./www/svg/ios-log-out.svg
rm ./www/svg/ios-magnet.svg
rm ./www/svg/ios-mail-open.svg
rm ./www/svg/ios-mail-unread.svg
rm ./www/svg/ios-mail.svg
rm ./www/svg/ios-male.svg
rm ./www/svg/ios-man.svg
rm ./www/svg/ios-map.svg
rm ./www/svg/ios-medal.svg
rm ./www/svg/ios-medical.svg
rm ./www/svg/ios-medkit.svg
rm ./www/svg/ios-megaphone.svg
rm ./www/svg/ios-menu.svg
rm ./www/svg/ios-mic-off.svg
rm ./www/svg/ios-mic.svg
rm ./www/svg/ios-microphone.svg
rm ./www/svg/ios-moon.svg
rm ./www/svg/ios-more.svg
rm ./www/svg/ios-move.svg
rm ./www/svg/ios-musical-note.svg
rm ./www/svg/ios-musical-notes.svg
rm ./www/svg/ios-navigate.svg
rm ./www/svg/ios-notifications-off.svg
rm ./www/svg/ios-notifications-outline.svg
rm ./www/svg/ios-notifications.svg
rm ./www/svg/ios-nuclear.svg
rm ./www/svg/ios-nutrition.svg
rm ./www/svg/ios-open.svg
rm ./www/svg/ios-options.svg
rm ./www/svg/ios-outlet.svg
rm ./www/svg/ios-paper-plane.svg
rm ./www/svg/ios-paper.svg
rm ./www/svg/ios-partly-sunny.svg
rm ./www/svg/ios-pause.svg
rm ./www/svg/ios-paw.svg
rm ./www/svg/ios-people.svg
rm ./www/svg/ios-person-add.svg
rm ./www/svg/ios-person.svg
rm ./www/svg/ios-phone-landscape.svg
rm ./www/svg/ios-phone-portrait.svg
rm ./www/svg/ios-photos.svg
rm ./www/svg/ios-pie.svg
rm ./www/svg/ios-pin.svg
rm ./www/svg/ios-pint.svg
rm ./www/svg/ios-planet.svg
rm ./www/svg/ios-play-circle.svg
rm ./www/svg/ios-play.svg
rm ./www/svg/ios-podium.svg
rm ./www/svg/ios-power.svg
rm ./www/svg/ios-pricetag.svg
rm ./www/svg/ios-pricetags.svg
rm ./www/svg/ios-print.svg
rm ./www/svg/ios-pulse.svg
rm ./www/svg/ios-qr-scanner.svg
rm ./www/svg/ios-quote.svg
rm ./www/svg/ios-radio-button-off.svg
rm ./www/svg/ios-radio-button-on.svg
rm ./www/svg/ios-radio.svg
rm ./www/svg/ios-rainy.svg
rm ./www/svg/ios-recording.svg
rm ./www/svg/ios-redo.svg
rm ./www/svg/ios-refresh-circle.svg
rm ./www/svg/ios-refresh.svg
rm ./www/svg/ios-remove-circle-outline.svg
rm ./www/svg/ios-remove-circle.svg
rm ./www/svg/ios-remove.svg
rm ./www/svg/ios-reorder.svg
rm ./www/svg/ios-repeat.svg
rm ./www/svg/ios-resize.svg
rm ./www/svg/ios-restaurant.svg
rm ./www/svg/ios-return-left.svg
rm ./www/svg/ios-return-right.svg
rm ./www/svg/ios-reverse-camera.svg
rm ./www/svg/ios-rewind.svg
rm ./www/svg/ios-ribbon.svg
rm ./www/svg/ios-rocket.svg
rm ./www/svg/ios-rose.svg
rm ./www/svg/ios-sad.svg
rm ./www/svg/ios-save.svg
rm ./www/svg/ios-school.svg
rm ./www/svg/ios-search.svg
rm ./www/svg/ios-send.svg
rm ./www/svg/ios-settings.svg
rm ./www/svg/ios-share-alt.svg
rm ./www/svg/ios-share.svg
rm ./www/svg/ios-shirt.svg
rm ./www/svg/ios-shuffle.svg
rm ./www/svg/ios-skip-backward.svg
rm ./www/svg/ios-skip-forward.svg
rm ./www/svg/ios-snow.svg
rm ./www/svg/ios-speedometer.svg
rm ./www/svg/ios-square-outline.svg
rm ./www/svg/ios-square.svg
rm ./www/svg/ios-star-half.svg
rm ./www/svg/ios-star-outline.svg
rm ./www/svg/ios-star.svg
rm ./www/svg/ios-stats.svg
rm ./www/svg/ios-stopwatch.svg
rm ./www/svg/ios-subway.svg
rm ./www/svg/ios-sunny.svg
rm ./www/svg/ios-swap.svg
rm ./www/svg/ios-switch.svg
rm ./www/svg/ios-sync.svg
rm ./www/svg/ios-tablet-landscape.svg
rm ./www/svg/ios-tablet-portrait.svg
rm ./www/svg/ios-tennisball.svg
rm ./www/svg/ios-text.svg
rm ./www/svg/ios-thermometer.svg
rm ./www/svg/ios-thumbs-down.svg
rm ./www/svg/ios-thumbs-up.svg
rm ./www/svg/ios-thunderstorm.svg
rm ./www/svg/ios-time.svg
rm ./www/svg/ios-timer.svg
rm ./www/svg/ios-today.svg
rm ./www/svg/ios-train.svg
rm ./www/svg/ios-transgender.svg
rm ./www/svg/ios-trash.svg
rm ./www/svg/ios-trending-down.svg
rm ./www/svg/ios-trending-up.svg
rm ./www/svg/ios-trophy.svg
rm ./www/svg/ios-tv.svg
rm ./www/svg/ios-umbrella.svg
rm ./www/svg/ios-undo.svg
rm ./www/svg/ios-unlock.svg
rm ./www/svg/ios-videocam.svg
rm ./www/svg/ios-volume-high.svg
rm ./www/svg/ios-volume-low.svg
rm ./www/svg/ios-volume-mute.svg
rm ./www/svg/ios-volume-off.svg
rm ./www/svg/ios-wallet.svg
rm ./www/svg/ios-warning.svg
rm ./www/svg/ios-watch.svg
rm ./www/svg/ios-water.svg
rm ./www/svg/ios-wifi.svg
rm ./www/svg/ios-wine.svg
rm ./www/svg/ios-woman.svg
rm ./www/svg/logo-android.svg
rm ./www/svg/logo-angular.svg
rm ./www/svg/logo-apple.svg
rm ./www/svg/logo-bitbucket.svg
rm ./www/svg/logo-bitcoin.svg
rm ./www/svg/logo-buffer.svg
rm ./www/svg/logo-chrome.svg
rm ./www/svg/logo-closed-captioning.svg
rm ./www/svg/logo-codepen.svg
rm ./www/svg/logo-css3.svg
rm ./www/svg/logo-designernews.svg
rm ./www/svg/logo-dribbble.svg
rm ./www/svg/logo-dropbox.svg
rm ./www/svg/logo-euro.svg
rm ./www/svg/logo-facebook.svg
rm ./www/svg/logo-flickr.svg
rm ./www/svg/logo-foursquare.svg
rm ./www/svg/logo-freebsd-devil.svg
rm ./www/svg/logo-game-controller-a.svg
rm ./www/svg/logo-game-controller-b.svg
rm ./www/svg/logo-google.svg
rm ./www/svg/logo-googleplus.svg
rm ./www/svg/logo-hackernews.svg
rm ./www/svg/logo-html5.svg
rm ./www/svg/logo-instagram.svg
rm ./www/svg/logo-ionic.svg
rm ./www/svg/logo-ionitron.svg
rm ./www/svg/logo-javascript.svg
rm ./www/svg/logo-markdown.svg
rm ./www/svg/logo-model-s.svg
rm ./www/svg/logo-no-smoking.svg
rm ./www/svg/logo-nodejs.svg
rm ./www/svg/logo-npm.svg
rm ./www/svg/logo-octocat.svg
rm ./www/svg/logo-pinterest.svg
rm ./www/svg/logo-playstation.svg
rm ./www/svg/logo-polymer.svg
rm ./www/svg/logo-python.svg
rm ./www/svg/logo-reddit.svg
rm ./www/svg/logo-rss.svg
rm ./www/svg/logo-sass.svg
rm ./www/svg/logo-skype.svg
rm ./www/svg/logo-slack.svg
rm ./www/svg/logo-snapchat.svg
rm ./www/svg/logo-steam.svg
rm ./www/svg/logo-tumblr.svg
rm ./www/svg/logo-tux.svg
rm ./www/svg/logo-twitch.svg
rm ./www/svg/logo-twitter.svg
rm ./www/svg/logo-usd.svg
rm ./www/svg/logo-vimeo.svg
rm ./www/svg/logo-vk.svg
rm ./www/svg/logo-whatsapp.svg
rm ./www/svg/logo-windows.svg
rm ./www/svg/logo-wordpress.svg
rm ./www/svg/logo-xbox.svg
rm ./www/svg/logo-xing.svg
rm ./www/svg/logo-yahoo.svg
rm ./www/svg/logo-yen.svg
rm ./www/svg/logo-youtube.svg
rm ./www/svg/md-add-circle-outline.svg
rm ./www/svg/md-add-circle.svg
rm ./www/svg/md-add.svg
rm ./www/svg/md-airplane.svg
rm ./www/svg/md-alarm.svg
rm ./www/svg/md-albums.svg
rm ./www/svg/md-alert.svg
rm ./www/svg/md-american-football.svg
rm ./www/svg/md-analytics.svg
rm ./www/svg/md-aperture.svg
rm ./www/svg/md-appstore.svg
rm ./www/svg/md-archive.svg
rm ./www/svg/md-arrow-back.svg
rm ./www/svg/md-arrow-down.svg
rm ./www/svg/md-arrow-dropdown-circle.svg
rm ./www/svg/md-arrow-dropdown.svg
rm ./www/svg/md-arrow-dropleft-circle.svg
rm ./www/svg/md-arrow-dropleft.svg
rm ./www/svg/md-arrow-dropright-circle.svg
rm ./www/svg/md-arrow-dropright.svg
rm ./www/svg/md-arrow-dropup-circle.svg
rm ./www/svg/md-arrow-dropup.svg
rm ./www/svg/md-arrow-forward.svg
rm ./www/svg/md-arrow-round-back.svg
rm ./www/svg/md-arrow-round-down.svg
rm ./www/svg/md-arrow-round-forward.svg
rm ./www/svg/md-arrow-round-up.svg
rm ./www/svg/md-arrow-up.svg
rm ./www/svg/md-at.svg
rm ./www/svg/md-attach.svg
rm ./www/svg/md-backspace.svg
rm ./www/svg/md-barcode.svg
rm ./www/svg/md-baseball.svg
rm ./www/svg/md-basket.svg
rm ./www/svg/md-basketball.svg
rm ./www/svg/md-battery-charging.svg
rm ./www/svg/md-battery-dead.svg
rm ./www/svg/md-battery-full.svg
rm ./www/svg/md-beaker.svg
rm ./www/svg/md-bed.svg
rm ./www/svg/md-beer.svg
rm ./www/svg/md-bicycle.svg
rm ./www/svg/md-bluetooth.svg
rm ./www/svg/md-boat.svg
rm ./www/svg/md-body.svg
rm ./www/svg/md-bonfire.svg
rm ./www/svg/md-book.svg
rm ./www/svg/md-bookmark.svg
rm ./www/svg/md-bookmarks.svg
rm ./www/svg/md-bowtie.svg
rm ./www/svg/md-briefcase.svg
rm ./www/svg/md-browsers.svg
rm ./www/svg/md-brush.svg
rm ./www/svg/md-bug.svg
rm ./www/svg/md-build.svg
rm ./www/svg/md-bulb.svg
rm ./www/svg/md-bus.svg
rm ./www/svg/md-business.svg
rm ./www/svg/md-cafe.svg
rm ./www/svg/md-calculator.svg
rm ./www/svg/md-calendar.svg
rm ./www/svg/md-call.svg
rm ./www/svg/md-camera.svg
rm ./www/svg/md-car.svg
rm ./www/svg/md-card.svg
rm ./www/svg/md-cart.svg
rm ./www/svg/md-cash.svg
rm ./www/svg/md-cellular.svg
rm ./www/svg/md-chatboxes.svg
rm ./www/svg/md-chatbubbles.svg
rm ./www/svg/md-checkbox-outline.svg
rm ./www/svg/md-checkbox.svg
rm ./www/svg/md-checkmark-circle-outline.svg
rm ./www/svg/md-checkmark-circle.svg
rm ./www/svg/md-checkmark.svg
rm ./www/svg/md-clipboard.svg
rm ./www/svg/md-clock.svg
rm ./www/svg/md-close-circle-outline.svg
rm ./www/svg/md-close-circle.svg
rm ./www/svg/md-close.svg
rm ./www/svg/md-cloud-circle.svg
rm ./www/svg/md-cloud-done.svg
rm ./www/svg/md-cloud-download.svg
rm ./www/svg/md-cloud-outline.svg
rm ./www/svg/md-cloud-upload.svg
rm ./www/svg/md-cloud.svg
rm ./www/svg/md-cloudy-night.svg
rm ./www/svg/md-cloudy.svg
rm ./www/svg/md-code-download.svg
rm ./www/svg/md-code-working.svg
rm ./www/svg/md-code.svg
rm ./www/svg/md-cog.svg
rm ./www/svg/md-color-fill.svg
rm ./www/svg/md-color-filter.svg
rm ./www/svg/md-color-palette.svg
rm ./www/svg/md-color-wand.svg
rm ./www/svg/md-compass.svg
rm ./www/svg/md-construct.svg
rm ./www/svg/md-contact.svg
rm ./www/svg/md-contacts.svg
rm ./www/svg/md-contract.svg
rm ./www/svg/md-contrast.svg
rm ./www/svg/md-copy.svg
rm ./www/svg/md-create.svg
rm ./www/svg/md-crop.svg
rm ./www/svg/md-cube.svg
rm ./www/svg/md-cut.svg
rm ./www/svg/md-desktop.svg
rm ./www/svg/md-disc.svg
rm ./www/svg/md-done-all.svg
rm ./www/svg/md-download.svg
rm ./www/svg/md-easel.svg
rm ./www/svg/md-egg.svg
rm ./www/svg/md-exit.svg
rm ./www/svg/md-expand.svg
rm ./www/svg/md-eye-off.svg
rm ./www/svg/md-eye.svg
rm ./www/svg/md-fastforward.svg
rm ./www/svg/md-female.svg
rm ./www/svg/md-filing.svg
rm ./www/svg/md-film.svg
rm ./www/svg/md-finger-print.svg
rm ./www/svg/md-fitness.svg
rm ./www/svg/md-flag.svg
rm ./www/svg/md-flame.svg
rm ./www/svg/md-flash-off.svg
rm ./www/svg/md-flash.svg
rm ./www/svg/md-flashlight.svg
rm ./www/svg/md-flask.svg
rm ./www/svg/md-flower.svg
rm ./www/svg/md-folder-open.svg
rm ./www/svg/md-folder.svg
rm ./www/svg/md-football.svg
rm ./www/svg/md-funnel.svg
rm ./www/svg/md-gift.svg
rm ./www/svg/md-git-branch.svg
rm ./www/svg/md-git-commit.svg
rm ./www/svg/md-git-compare.svg
rm ./www/svg/md-git-merge.svg
rm ./www/svg/md-git-network.svg
rm ./www/svg/md-git-pull-request.svg
rm ./www/svg/md-glasses.svg
rm ./www/svg/md-globe.svg
rm ./www/svg/md-grid.svg
rm ./www/svg/md-hammer.svg
rm ./www/svg/md-hand.svg
rm ./www/svg/md-happy.svg
rm ./www/svg/md-headset.svg
rm ./www/svg/md-heart-dislike.svg
rm ./www/svg/md-heart-empty.svg
rm ./www/svg/md-heart-half.svg
rm ./www/svg/md-heart.svg
rm ./www/svg/md-help-buoy.svg
rm ./www/svg/md-help-circle-outline.svg
rm ./www/svg/md-help-circle.svg
rm ./www/svg/md-help.svg
rm ./www/svg/md-home.svg
rm ./www/svg/md-hourglass.svg
rm ./www/svg/md-ice-cream.svg
rm ./www/svg/md-image.svg
rm ./www/svg/md-images.svg
rm ./www/svg/md-infinite.svg
rm ./www/svg/md-information-circle-outline.svg
rm ./www/svg/md-information-circle.svg
rm ./www/svg/md-information.svg
rm ./www/svg/md-jet.svg
rm ./www/svg/md-journal.svg
rm ./www/svg/md-key.svg
rm ./www/svg/md-keypad.svg
rm ./www/svg/md-laptop.svg
rm ./www/svg/md-leaf.svg
rm ./www/svg/md-list-box.svg
rm ./www/svg/md-list.svg
rm ./www/svg/md-locate.svg
rm ./www/svg/md-lock.svg
rm ./www/svg/md-log-in.svg
rm ./www/svg/md-log-out.svg
rm ./www/svg/md-magnet.svg
rm ./www/svg/md-mail-open.svg
rm ./www/svg/md-mail-unread.svg
rm ./www/svg/md-mail.svg
rm ./www/svg/md-male.svg
rm ./www/svg/md-man.svg
rm ./www/svg/md-map.svg
rm ./www/svg/md-medal.svg
rm ./www/svg/md-medical.svg
rm ./www/svg/md-medkit.svg
rm ./www/svg/md-megaphone.svg
rm ./www/svg/md-menu.svg
rm ./www/svg/md-mic-off.svg
rm ./www/svg/md-mic.svg
rm ./www/svg/md-microphone.svg
rm ./www/svg/md-moon.svg
rm ./www/svg/md-more.svg
rm ./www/svg/md-move.svg
rm ./www/svg/md-musical-note.svg
rm ./www/svg/md-musical-notes.svg
rm ./www/svg/md-navigate.svg
rm ./www/svg/md-notifications-off.svg
rm ./www/svg/md-notifications-outline.svg
rm ./www/svg/md-notifications.svg
rm ./www/svg/md-nuclear.svg
rm ./www/svg/md-nutrition.svg
rm ./www/svg/md-open.svg
rm ./www/svg/md-options.svg
rm ./www/svg/md-outlet.svg
rm ./www/svg/md-paper-plane.svg
rm ./www/svg/md-paper.svg
rm ./www/svg/md-partly-sunny.svg
rm ./www/svg/md-pause.svg
rm ./www/svg/md-paw.svg
rm ./www/svg/md-people.svg
rm ./www/svg/md-person-add.svg
rm ./www/svg/md-person.svg
rm ./www/svg/md-phone-landscape.svg
rm ./www/svg/md-phone-portrait.svg
rm ./www/svg/md-photos.svg
rm ./www/svg/md-pie.svg
rm ./www/svg/md-pin.svg
rm ./www/svg/md-pint.svg
rm ./www/svg/md-planet.svg
rm ./www/svg/md-play-circle.svg
rm ./www/svg/md-play.svg
rm ./www/svg/md-podium.svg
rm ./www/svg/md-power.svg
rm ./www/svg/md-pricetag.svg
rm ./www/svg/md-pricetags.svg
rm ./www/svg/md-print.svg
rm ./www/svg/md-pulse.svg
rm ./www/svg/md-qr-scanner.svg
rm ./www/svg/md-quote.svg
rm ./www/svg/md-radio-button-off.svg
rm ./www/svg/md-radio-button-on.svg
rm ./www/svg/md-radio.svg
rm ./www/svg/md-rainy.svg
rm ./www/svg/md-recording.svg
rm ./www/svg/md-redo.svg
rm ./www/svg/md-refresh-circle.svg
rm ./www/svg/md-refresh.svg
rm ./www/svg/md-remove-circle-outline.svg
rm ./www/svg/md-remove-circle.svg
rm ./www/svg/md-remove.svg
rm ./www/svg/md-reorder.svg
rm ./www/svg/md-repeat.svg
rm ./www/svg/md-resize.svg
rm ./www/svg/md-restaurant.svg
rm ./www/svg/md-return-left.svg
rm ./www/svg/md-return-right.svg
rm ./www/svg/md-reverse-camera.svg
rm ./www/svg/md-rewind.svg
rm ./www/svg/md-ribbon.svg
rm ./www/svg/md-rocket.svg
rm ./www/svg/md-rose.svg
rm ./www/svg/md-sad.svg
rm ./www/svg/md-save.svg
rm ./www/svg/md-school.svg
rm ./www/svg/md-search.svg
rm ./www/svg/md-send.svg
rm ./www/svg/md-settings.svg
rm ./www/svg/md-share-alt.svg
rm ./www/svg/md-share.svg
rm ./www/svg/md-shirt.svg
rm ./www/svg/md-shuffle.svg
rm ./www/svg/md-skip-backward.svg
rm ./www/svg/md-skip-forward.svg
rm ./www/svg/md-snow.svg
rm ./www/svg/md-speedometer.svg
rm ./www/svg/md-square-outline.svg
rm ./www/svg/md-square.svg
rm ./www/svg/md-star-half.svg
rm ./www/svg/md-star-outline.svg
rm ./www/svg/md-star.svg
rm ./www/svg/md-stats.svg
rm ./www/svg/md-stopwatch.svg
rm ./www/svg/md-subway.svg
rm ./www/svg/md-sunny.svg
rm ./www/svg/md-swap.svg
rm ./www/svg/md-switch.svg
rm ./www/svg/md-sync.svg
rm ./www/svg/md-tablet-landscape.svg
rm ./www/svg/md-tablet-portrait.svg
rm ./www/svg/md-tennisball.svg
rm ./www/svg/md-text.svg
rm ./www/svg/md-thermometer.svg
rm ./www/svg/md-thumbs-down.svg
rm ./www/svg/md-thumbs-up.svg
rm ./www/svg/md-thunderstorm.svg
rm ./www/svg/md-time.svg
rm ./www/svg/md-timer.svg
rm ./www/svg/md-today.svg
rm ./www/svg/md-train.svg
rm ./www/svg/md-transgender.svg
rm ./www/svg/md-trash.svg
rm ./www/svg/md-trending-down.svg
rm ./www/svg/md-trending-up.svg
rm ./www/svg/md-trophy.svg
rm ./www/svg/md-tv.svg
rm ./www/svg/md-umbrella.svg
rm ./www/svg/md-undo.svg
rm ./www/svg/md-unlock.svg
rm ./www/svg/md-videocam.svg
rm ./www/svg/md-volume-high.svg
rm ./www/svg/md-volume-low.svg
rm ./www/svg/md-volume-mute.svg
rm ./www/svg/md-volume-off.svg
rm ./www/svg/md-wallet.svg
rm ./www/svg/md-warning.svg
rm ./www/svg/md-watch.svg
rm ./www/svg/md-water.svg
rm ./www/svg/md-wifi.svg
rm ./www/svg/md-wine.svg
rm ./www/svg/md-woman.svg
